"""{message}

Revision ID: 0d9fcf3c4faf
Revises: 
Create Date: 2024-10-29 22:55:57.597559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9fcf3c4faf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('cocarts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('allow_vote', sa.Boolean(), nullable=False),
    sa.Column('allow_add_product', sa.Boolean(), nullable=False),
    sa.Column('allow_remove_product', sa.Boolean(), nullable=False),
    sa.Column('mark_purchased_items', sa.Boolean(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_hide', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_cocarts_id'), 'cocarts', ['id'], unique=False)
    op.create_index(op.f('ix_cocarts_user_id'), 'cocarts', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('original_price', sa.Double(), nullable=True),
    sa.Column('customer_rating', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Double(), nullable=True),
    sa.Column('product_tracking_url', sa.String(length=2500), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('product_source', sa.Integer(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('standard_shipping_rate', sa.String(length=255), nullable=True),
    sa.Column('size', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('marketplace', sa.Integer(), nullable=True),
    sa.Column('model_number', sa.String(length=255), nullable=True),
    sa.Column('seller_info', sa.String(length=255), nullable=True),
    sa.Column('number_of_reviews', sa.Integer(), nullable=True),
    sa.Column('rhid', sa.String(length=255), nullable=True),
    sa.Column('bundle', sa.Boolean(), nullable=True),
    sa.Column('clearance', sa.Boolean(), nullable=True),
    sa.Column('preorder', sa.Boolean(), nullable=True),
    sa.Column('stock', sa.String(length=255), nullable=True),
    sa.Column('freight', sa.Boolean(), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('affiliate_add_to_cart_url', sa.String(length=2500), nullable=True),
    sa.Column('max_number_of_qty', sa.Integer(), nullable=True),
    sa.Column('offer_type', sa.Integer(), nullable=True),
    sa.Column('available_online', sa.Boolean(), nullable=True),
    sa.Column('e_delivery', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('wm_product_id', sa.String(length=255), nullable=True),
    sa.Column('amazon_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('cocart_products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cocart_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_bought', sa.Boolean(), nullable=False),
    sa.Column('is_claimed', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cocart_id'], ['cocarts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cocart_products_cocart_id'), 'cocart_products', ['cocart_id'], unique=False)
    op.create_index(op.f('ix_cocart_products_id'), 'cocart_products', ['id'], unique=False)
    op.create_index(op.f('ix_cocart_products_product_id'), 'cocart_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_cocart_products_user_id'), 'cocart_products', ['user_id'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('medium_image', sa.String(length=255), nullable=True),
    sa.Column('large_image', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_cocart_products_user_id'), table_name='cocart_products')
    op.drop_index(op.f('ix_cocart_products_product_id'), table_name='cocart_products')
    op.drop_index(op.f('ix_cocart_products_id'), table_name='cocart_products')
    op.drop_index(op.f('ix_cocart_products_cocart_id'), table_name='cocart_products')
    op.drop_table('cocart_products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_cocarts_user_id'), table_name='cocarts')
    op.drop_index(op.f('ix_cocarts_id'), table_name='cocarts')
    op.drop_table('cocarts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
