"""removed unique constaint

Revision ID: 1c0dc9ff91c4
Revises: 6471a96618e1
Create Date: 2024-10-23 14:47:15.314007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c0dc9ff91c4'
down_revision: Union[str, None] = '6471a96618e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_product_title', table_name='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_product_title', 'products', ['product_title'], unique=True)
    # ### end Alembic commands ###
