"""{message}

Revision ID: 6471a96618e1
Revises: 8dea73956b1b
Create Date: 2024-10-23 14:40:01.625283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6471a96618e1'
down_revision: Union[str, None] = '8dea73956b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'current_price',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('products', 'mrp_price',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('products', 'rating',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_products_product_title'), 'products', ['product_title'], unique=True)
    op.create_unique_constraint('uq_product_title', 'products', ['product_title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_title', 'products', type_='unique')
    op.drop_index(op.f('ix_products_product_title'), table_name='products')
    op.alter_column('products', 'rating',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('products', 'mrp_price',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('products', 'current_price',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
