"""removed unique constaint1

Revision ID: 6f6493a03eb5
Revises: 1c0dc9ff91c4
Create Date: 2024-10-23 14:47:59.713982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f6493a03eb5'
down_revision: Union[str, None] = '1c0dc9ff91c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_product_title', table_name='products')
    op.create_index(op.f('ix_products_product_title'), 'products', ['product_title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_product_title'), table_name='products')
    op.create_index('ix_products_product_title', 'products', ['product_title'], unique=True)
    # ### end Alembic commands ###
