"""Added indexes to optimize wishlist queries

Revision ID: 8dea73956b1b
Revises: de2e69651543
Create Date: 2024-10-22 21:25:49.509919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dea73956b1b'
down_revision: Union[str, None] = 'de2e69651543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_wishlist_products_product_id'), 'wishlist_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_wishlist_products_wishlist_id'), 'wishlist_products', ['wishlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wishlist_products_wishlist_id'), table_name='wishlist_products')
    op.drop_index(op.f('ix_wishlist_products_product_id'), table_name='wishlist_products')
    # ### end Alembic commands ###
