"""added note in product model

Revision ID: b91a27176f06
Revises: bef52f4e81c3
Create Date: 2024-10-23 22:13:14.774450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b91a27176f06'
down_revision: Union[str, None] = 'bef52f4e81c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'note')
    # ### end Alembic commands ###
