"""renamed product_title to title

Revision ID: bef52f4e81c3
Revises: 6f6493a03eb5
Create Date: 2024-10-23 15:26:19.946503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bef52f4e81c3'
down_revision: Union[str, None] = '6f6493a03eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('title', sa.String(length=255), nullable=False))
    op.drop_index('ix_products_product_title', table_name='products')
    op.create_index(op.f('ix_products_title'), 'products', ['title'], unique=False)
    op.drop_column('products', 'product_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_title', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_products_title'), table_name='products')
    op.create_index('ix_products_product_title', 'products', ['product_title'], unique=False)
    op.drop_column('products', 'title')
    # ### end Alembic commands ###
