"""cocart schema

Revision ID: f62492e8b00f
Revises: 28c234e121f0
Create Date: 2024-10-29 14:27:49.363024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f62492e8b00f'
down_revision: Union[str, None] = '28c234e121f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cocarts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cocarts_id'), 'cocarts', ['id'], unique=False)
    op.create_table('cocart_products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cocart_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cocart_id'], ['cocarts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cocart_products_cocart_id'), 'cocart_products', ['cocart_id'], unique=False)
    op.create_index(op.f('ix_cocart_products_id'), 'cocart_products', ['id'], unique=False)
    op.create_index(op.f('ix_cocart_products_product_id'), 'cocart_products', ['product_id'], unique=False)
    op.drop_index('ix_wishlists_id', table_name='wishlists')
    op.drop_table('wishlists')
    op.drop_index('ix_wishlist_products_id', table_name='wishlist_products')
    op.drop_index('ix_wishlist_products_product_id', table_name='wishlist_products')
    op.drop_index('ix_wishlist_products_wishlist_id', table_name='wishlist_products')
    op.drop_table('wishlist_products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist_products',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('wishlist_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('note', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='wishlist_products_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], name='wishlist_products_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_wishlist_products_wishlist_id', 'wishlist_products', ['wishlist_id'], unique=False)
    op.create_index('ix_wishlist_products_product_id', 'wishlist_products', ['product_id'], unique=False)
    op.create_index('ix_wishlist_products_id', 'wishlist_products', ['id'], unique=False)
    op.create_table('wishlists',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wishlists_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_wishlists_id', 'wishlists', ['id'], unique=False)
    op.drop_index(op.f('ix_cocart_products_product_id'), table_name='cocart_products')
    op.drop_index(op.f('ix_cocart_products_id'), table_name='cocart_products')
    op.drop_index(op.f('ix_cocart_products_cocart_id'), table_name='cocart_products')
    op.drop_table('cocart_products')
    op.drop_index(op.f('ix_cocarts_id'), table_name='cocarts')
    op.drop_table('cocarts')
    # ### end Alembic commands ###
